### ISSUE TITLE
Review RUCA Board Paper

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/documentation#113]
Please review board paper in RUCA folder in our Google Drive.

**Comment by ClaireTroughtonJAC** [comment]
CT completed draft comments on paper.  Over to TT and US for comment

**Comment by UmeshxSolanki** [comment]
Added my comments.

**Comment by tatyree** [comment]
I have reviewed and have nothing to add.
