### ISSUE TITLE
Staff Suggestion:  Replace Survey Monkey with Google Forms

### ISSUE THREAD

**Issue by UmeshxSolanki** [JudicialAppointmentsCommission/documentation#114]
### Background

From Ops Management Meeting on 2nd Nov 2018, and JAC Staff Suggestions:

Suggestion date:
02 October 2018	
Suggestion:
As a way to save money, what if we use Google forms to collate responses from candidates following key points, such as a sift, selection day etc rather than using survey monkey?
I understand it can do the same as survey monkey and it is free to use.
We could make sure we download and save all relevant survey monkey results before losing access to them once the contract or bill is no longer paid.
	
Action point: 
Digital team to consider

**Comment by ClaireTroughtonJAC** [comment]
Nora B has tested this previously.  Suggest whoever picks up the ticket, liaise with her first.
