### ISSUE TITLE
Hire and onboard a user researcher

### ISSUE THREAD

**Issue by tatyree** [JudicialAppointmentsCommission/documentation#24]
depends on #33

Placeholder for the moment.

**Comment by UmeshxSolanki** [comment]
requires #33

**Comment by tatyree** [comment]
It is pending approval on fieldglass now - PSR1JP00010474.

**Comment by tatyree** [comment]
PSR chased me just now as I forgot to upload the IR35 statement.  That's now done and it's back in progress.

**Comment by tatyree** [comment]
And I've realised that fieldglass has listed the position at a rate that exceeds both the signed off rate AND the maximum rate on the rate card.  I've raised it with PSR to get it amended as the target rate was what was agreed.

**Comment by tatyree** [comment]
Interviews scheduled.

**Comment by tatyree** [comment]
User Researcher interview worksheet: 

https://docs.google.com/document/d/1SflInm9R5-Y8qXqpiKm2Ju5Z5pgtqpjGl_-604CPCcs/edit

I'm moving this back to 'To Do' until we're conducting the interviews.

**Comment by tatyree** [comment]
First interviewee cancelled.  Have asked PSR for additional CVs.

**Comment by tatyree** [comment]
Candidate has accepted.  I've proposed a start date of 2019-01-07, which is the first Monday back.  Waiting on PSR to confirm. 

TODO: Ensure PSR have the the correct people set up as timesheet approvers on Fieldglass.
