### ISSUE TITLE
Work up summary budget through until March 2019

### ISSUE THREAD

**Issue by tatyree** [JudicialAppointmentsCommission/documentation#40]
required by #31
required by #32

In support of the business cases for the developer and user researchers and based on the savings made from the savings on contracts.

**Comment by tatyree** [comment]
Adapt the current spreadsheet to summarise savings vs. spend for Sharon.

**Comment by tatyree** [comment]
I've sent the spreadsheet and doc to Sharon to action.  I'm going to leave this open until it's sent.  

Also, going to try to call Sophia Jenkins about it to give her a heads up.

**Comment by tatyree** [comment]
Business case and IR35 papers are now all to Sharon as well. 

I cannot get through to Sophia about this.  She called me back earlier this week, but now her phone just disconnects after ringing a few times.  I've emailed her as well.

**Comment by tatyree** [comment]
Sharon and Ian have both now emailed to say they are satisfied with this.  Closing.

**Comment by UmeshxSolanki** [comment]
Who is Sophia Jenkins?
