### ISSUE TITLE
SIRO Approval for  QT

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/documentation#57]
We need formal approval to use Google for the QT following current security policy.

**Comment by ClaireTroughtonJAC** [comment]
SIRO will require:  

Assurance around Google security credentials
any links to our existing business application

**Comment by tatyree** [comment]
Google Forms has ISO27001 certification: https://cloud.google.com/security/compliance/iso-27001/

We may be using firebase cloud functions for some lower-level logging.  Compliance statements are here: https://firebase.google.com/support/privacy/

Google GDPR information: https://cloud.google.com/security/gdpr/

Link to the first use of Forms (pending) here: https://docs.google.com/forms/d/1kjsNP1DGy4R4nmlhjis1nFnPnHJQ40XwMWADfcMDrQg/edit

SIRO will need a G-suite account and a walkthrough I suspect.
