### ISSUE TITLE
Peer review researcher Business Case

### ISSUE THREAD

**Issue by UmeshxSolanki** [JudicialAppointmentsCommission/documentation#66]
requires #32
required by #33

**Comment by UmeshxSolanki** [comment]
I would also like to review it, before it gets closed.  Thus, re-opened this.

**Comment by tatyree** [comment]
@UmeshxSolanki I'm going to go ahead and close the ticket as the SLT have it.  You'll have an opportunity to give feedback again when we work up the job description and put it on fieldglass.

**Comment by UmeshxSolanki** [comment]
As we discussed, I reviewed the Business Case and have added quite a few comments.  Largely they are around if we have answered the actual question and in one area we have written about a Developer instead of a User Researcher.    

However, the intention is to get the budget, and if we've got that it the comments do not matter.  Unless we want to also use it to make sure we are getting the right person and can manage them effectively which has SLT buy-in.
