### ISSUE TITLE
Assess use of Robotics Process Automation

### ISSUE THREAD

**Issue by UmeshxSolanki** [JudicialAppointmentsCommission/documentation#68]
### Background
Cabinet office have an RPA team with a big consultancy who can come in and make an assessment of the viability of using these RPAs.  

- [X] Speak to SFK
- [ ] Speak to Kas about areas where we could potentially use this.  
- [ ] Write up outcome
- [ ] Open dialogue with the team

**Comment by sfofox** [comment]
Not at all urgent, consider post alpha?

**Comment by tatyree** [comment]
@sfofox Agreed.  I'm going to close this one for now.  We can revisit it later.

**Comment by UmeshxSolanki** [comment]
If we are going to re-visit this and it is low priority, is it not best just to sit at the bottom of the Inbox?

**Comment by tatyree** [comment]
I'm going to close this one as there isn't an identifiable user need and we already have access to very good process automation tools via AWS and Google without the need to involve third-party commercial relationships in other departments.
