### ISSUE TITLE
Updating Commission Board?

### ISSUE THREAD

**Issue by UmeshxSolanki** [JudicialAppointmentsCommission/documentation#73]
How will the digital team update the Commission Board?  

What do we do with the JARS Programme Board? 

Do we have a new meeting, or do they join an existing one?

**Comment by ClaireTroughtonJAC** [comment]
Please review the draft document

https://docs.google.com/document/d/1zH666_-BNzduLazb2EBcKbFIMxXLrAmRuKjUE01daxo/edit

**Comment by UmeshxSolanki** [comment]
I have completed the review.
