### ISSUE TITLE
Substitution Clause for contracts

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/documentation#74]
Todd to provide wording form Developer and Researcher contracts to Ian

**Comment by tatyree** [comment]
Emailed to Ian, Richard and @ClaireTroughtonJAC at 11:36 on 2018-10-29 as a docx. 

It can also be found here:

https://docs.google.com/document/d/1wu614GVmZp5WNVVa0Cktsn8BGN2nWBegiJYr3l-YhlY/edit?usp=sharing

It was taken from my most recent full contract with MoJ Digital and meets the test that the substitution is reasonable.  It also exposes the supplier to financial risk in the event of a failure (this is one of the tests from the supplier's perspective and so is something they'll be looking for).
