### ISSUE TITLE
Review Convivio Handover Plan

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [JudicialAppointmentsCommission/documentation#75]
##Background

Convivio have drafted a handover plan and Todd needs to review and ask any follow up questions.

**Comment by tatyree** [comment]
I've reviewed the handover document: 

https://drive.google.com/a/judicialappointments.digital/file/d/1J3sZok-TTJVSo3onrCQIVFReBY-7ToFu/view?usp=sharing

I don't see anything particularly worrying, although some of the items should be broken out in to tickets, here.
