### ISSUE TITLE
Write up findings from the two postmortems

### ISSUE THREAD

**Issue by tatyree** [JudicialAppointmentsCommission/documentation#86]
## Background 

We ran two postmortems on 2018-10-30.  Details can be found here: 

https://drive.google.com/drive/u/0/folders/0AAn1hbRIW4_hUk9PVA

All of the details are current in photos of post-its.  These need to be written up as tickets/recommendation or passed over to policy for inclusion in their templates. 

Assigned this to the JARS BAU Milestone because almost all of the actions relation to JARS's operation or our procedures around it.

**Comment by UmeshxSolanki** [comment]
From a conversation with Richard C. It looks like asking the Judges to limit the block of text is not sensible, and its the way it is created that really matters.
